# Generated by Django 4.2.30 on 2026-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=25, help_text='Total cooking time in minutes.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
